// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-6-lbEhlueeP-rGpl4gZQ7frMNAK85MQ',
    appId: '1:795953719810:web:f501501d83a879020e551b',
    messagingSenderId: '795953719810',
    projectId: 'thuchanhtuan5-85cbf',
    authDomain: 'thuchanhtuan5-85cbf.firebaseapp.com',
    storageBucket: 'thuchanhtuan5-85cbf.firebasestorage.app',
    measurementId: 'G-CPH23HHH9B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASC8gALT1uXwfdxpsgy_t6TkGVXbPBO0g',
    appId: '1:795953719810:android:e9f8268e8bd2b8fa0e551b',
    messagingSenderId: '795953719810',
    projectId: 'thuchanhtuan5-85cbf',
    storageBucket: 'thuchanhtuan5-85cbf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYGOPj7YVS6Iot5jF6dm5BG9JkURI82F4',
    appId: '1:795953719810:ios:2c31a75044259b270e551b',
    messagingSenderId: '795953719810',
    projectId: 'thuchanhtuan5-85cbf',
    storageBucket: 'thuchanhtuan5-85cbf.firebasestorage.app',
    iosBundleId: 'com.example.tuan51',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYGOPj7YVS6Iot5jF6dm5BG9JkURI82F4',
    appId: '1:795953719810:ios:2c31a75044259b270e551b',
    messagingSenderId: '795953719810',
    projectId: 'thuchanhtuan5-85cbf',
    storageBucket: 'thuchanhtuan5-85cbf.firebasestorage.app',
    iosBundleId: 'com.example.tuan51',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC-6-lbEhlueeP-rGpl4gZQ7frMNAK85MQ',
    appId: '1:795953719810:web:c7ebbd3fb6a68a600e551b',
    messagingSenderId: '795953719810',
    projectId: 'thuchanhtuan5-85cbf',
    authDomain: 'thuchanhtuan5-85cbf.firebaseapp.com',
    storageBucket: 'thuchanhtuan5-85cbf.firebasestorage.app',
    measurementId: 'G-8S0VW6FDYS',
  );
}
